export const TAPPLET_REGISTRY_REPO = 'tapp-registry'
export const BASE_BRANCH = 'main'
export const PR_TITLE_PREFIX = 'New Tapplet:'
export const SRC_DIR = 'src'
export const IMAGES_DIR = 'images'
export const VER_DIR = 'versions'
export const MANIFEST_FILE = 'tapplet.manifest.json'
