name: 'Register Tapplet'

on:
  workflow_dispatch:
    inputs:
      packageName:
        description: 'Tapplet package name'
        required: true
        default: 'tapplet-example'

  push:
    branches:
      - main

permissions:
  actions: write
  contents: write # to generate json file

jobs:
  register-tapplet:
    name: Registry Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        id: setup-node
        uses: actions/setup-node@v4
        with:
          node-version-file: .node-version
          cache: npm

      - name: Install Dependencies
        id: npm-ci
        run: npm ci

      - name: Add tapplet to the registry
        id: add-tapp
        uses: ./
        with:
          package-name: ${{ inputs.package-name }}
          package-url: ${{ inputs.package-url }}
          manifest-version: ${{ inputs.manifest-ersion }}

      - name: Print Output
        id: status
        run: echo "${{ steps.test-action.outputs.status }}"

      - name: Commit manifest
        id: make-commit
        run: |
          git config user.name "karczuRF"
          git config user.email "${{ secrets.EMAIL }}"
          git add -A
          git commit -m "Prepare release v2.0.4"

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          EMAIL: ${{ secrets.EMAIL }}
